sudiptasarkar011/FusionVision

index.html

This is the updated favicon, please add Labels like SWOC or BEGINNER before merging the PR to the main branch. @sudiptasarkar011

ADD Favicon

---

about.html
camera.html
contact.html
index.html
styles.css

This is the updated footer section, I requested you to please first assign the labels then merge the PR because after merging the PR the labels you assign won't count the points. @sudiptasarkar011

Updating Footer Section

---

index.html
package.json

Stopped the homepage narration

---

about.html
contact.html

@sudiptasarkar011 
i made changes in contact.html and about.html to make social media icons visible ,
please review it and merge it.
Thank you

#19adding social media icons in about.html,contact.html

---

index.html
reviews.html

closes: #31 
Page Layout and Design:
A central container holds the content with a clean, minimalist design.
Background: Animated subtle background to keep the focus on content.
Tabs for Navigation: "Latest Reviews" and "Top Reviews" tabs allow users to switch between reviews.
2. Reviews Section:
Review Cards: Each review contains a title, author, content, and date.
Reviews are displayed in a two-column layout for better space utilization.
3. Comments Section:
Users can submit feedback via a comment form with a textarea and submit button.
Dynamic comment list: New comments are added in real-time with timestamps.
4. JavaScript Features:
Dynamic Commenting: Allows for real-time comment submission without page refresh.
Form Validation: Prevents empty comments from being submitted.
5. Styling: …

Added Testimonials page

---

contact.html
privacyp.html
styles.css

Fixed Privacy policy page @sudiptasarkar011 Add SWOC levels to this PR 
Screenrecording :
https://github.com/user-attachments/assets/de8add24-a830-4971-afc2-a7bbbdcd417e

Add privacy policy page

---

features.html

Features web page #8

---

about.html
camera.html
contact.html
privacyp.html
whoweare.html

Added and linked the Who We Are page to the footer in all pages. Please check and merge my PR.

Added Who We Are page

---

.env
index.html

fix issue #58 
Resolved the issue of incorrect commenting caused by JavaScript code displaying on the website.

Incorrect Commenting Issue Resolved

---

about.html
camera.html
contact.html
features.html
index.html
privacyp.html
reviews.html

I updated the UI of the contact us form and made it look a bit more presentable and easier to access. (I'm a noob but at least this version's better than the previous version, right?) I also linked it to the "Contact Us" button in the footer. Please check if the update is good enough :)

Updated UI of Contact page 

---

camera.html

Added hover in the buttons of scanner control as i have raised the issue related to it  and added links and icons in footer section which were missing the start.

Added hover to buttons of scanner controls and icons and links to follow us section in footer

---

index.html
script.js
styles.css

**issue no: #65**
This pull request introduces a **scroll-to-top button** to the homepage, enhancing navigation for users. The button improves user experience by allowing easy and quick navigation to the top of the page, especially for pages with long content.
---
1. **Dynamic Visibility:**  
- The scroll button is only visible when the user scrolls down a certain distance from the top of the page.
- It disappears when the user returns to the top, ensuring a clutter-free interface.
2. **Smooth Scrolling:**  
- Clicking the button smoothly scrolls the user back to the top, providing a seamless navigation experience.
3. **Responsive Design:**  
- The button is styled to look appealing and functions consistently across all screen sizes and devices.
4. **Customizable Appearance:**  
- The …

Add Scroll-to-Top Button to Homepage

---

Terms.html
index.html

Fixed Terms of Service page to the website @sudiptasarkar011 Add SWOC levels to this PR 
Screenrecording  
https://github.com/user-attachments/assets/6fded9e4-c6bd-42f2-ae1b-e9c85de8de0d

Add terms of  Service page 

---

reviews.html

Resolved issues on the reviews.html page. Updated the navbar and footer.

---

features.html
styles.css

The previous layout displayed six items in a single row, with the seventh item forced into a new row. This configuration resulted in inconsistent alignment and visual imbalance, particularly due to the varying shapes of the items.
The layout has been refactored to display four items in the first row and three items in the second row, ensuring a more symmetrical and aesthetically pleasing arrangement.
Adjustments were made to the item shapes to maintain uniformity across the layout, improving overall visual consistency.
Fixes the issue #73  
after changing

changed  features style #73

---

about.html
contact.html
features.html
index.html
privacyp.html
reviews.html
styles.css

updated all footers

---

contributor.css
contributor.html
contributor.js
index.html

Hey👋 @sudiptasarkar011
issue has been fixed!
https://github.com/user-attachments/assets/1dbaec83-0f7c-403f-b3e8-a717c7ff450d

Add Contributor page

---

Terms.html
about.html
blog.html
features.html
index.html
privacyp.html
reviews.html
whoweare.html
workwithus.html

i have resolved the footer issue in blog and workwith us pages and also i have changed the year 2024 to 2025 in footer.
https://github.com/user-attachments/assets/33aeb364-8c8d-4198-b03d-1a3c6967c467

fixed footer in blog and workwith us pages

---

.vscode/settings.json
about.html
contact.html
features.html
index.html
reviews.html
script.js
signIn.html
signUp.html
styles.css

**fixed issue #1**
**Description:**
In this PR, I have fixed the background of the Sign-in and Sign-up pages to enhance the visual consistency and overall user experience. The background has been updated to a more cohesive and appealing design, ensuring it aligns with the overall theme of the website. 
**Key Changes:**
- 📱 Updated the background styling for both Sign-in and Sign-up pages.
- 🎨 Improved UI by applying a more consistent background pattern/color.
- 🧑‍💻 Ensured the pages' aesthetics are now aligned with the rest of the website.
- 🔄 Added smooth responsiveness for different screen sizes.
This update improves the user interface by providing a more professional and engaging look, helping visitors have a seamless experience while interacting with these pages.
**preview**
---
---

✨ Fixed Background of Sign-in and Sign-up Pages ✨

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_bug.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question_and_support.yml
.github/PULL_REQUEST_TEMPLATE.md

**Summary**  
This PR adds the necessary standardized issue and pull request templates to the repository. The following templates have been created:  
1. **Bug Report Template**: Includes fields for Description, Steps to Reproduce, Expected Behavior, Actual Behavior, Screenshots, and Environment Details.  
2. **Feature Request Template**: Includes fields for Feature Description, Use Case, Proposed Solution, and Alternatives Considered.  
3. **Custom Template for Enhancements or Documentation Updates**: Tailored to collect detailed information for enhancements or documentation-related updates.  
**Related Issues**  
Closes #105 
**Changes Made**  
- Added `.github/ISSUE_TEMPLATE/bug_report.yml` for bug report issues.
- Added `.github/ISSUE_TEMPLATE/feature_request.yml` for feature …

Add Standardized Issue and Pull Request Templates (Closes #105)

---

about.html

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

updated the about page

---

index.html

i have changed the text color in navbar and footer in the dark mode.
Fixes # (issue)
Please delete options that are not relevant.
- [ y] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my own code
- [ y] I have commented my code, particularly in hard-to-understand areas
- [ y] I have made corresponding changes to the documentation
- [ y] My changes generate no new warnings
- [ y] I have added tests that prove my fix is effective or that my feature works
- [y ] New and existing unit tests pass locally with my changes
- [y ] Any dependent changes have been merged and published in downstream modules

changed text color

---

index.html
styles.css

When dark mode is activated, the text color switches to white to ensure readability against the darker background. This fix ensures better accessibility and a more consistent dark mode experience. Originally, the focus was only on changing the text color of the navigation bar, but the footer text color was also modified for consistency. 
Change of text color for navigation :
Change of text color for footer:

Updated Navigation and Footer Text Color for Dark Mode
